{
 "title": "Netgear Cable Modem",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DS Power (avg)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(netgear_cm_downstream_channel_power_dbmv > 0)"
    }
   ]
  },
  {
   "title": "DS SnR (avg)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(netgear_cm_downstream_channel_snr_db > 0)"
    }
   ]
  },
  {
   "title": "DS Correctable Codewords (1d)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(netgear_cm_downstream_channel_correctable_codewords_total[1d]))"
    }
   ]
  },
  {
   "title": "DS Uncorrectable Codewords (1d)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(netgear_cm_downstream_channel_uncorrectable_codewords_total[1d]))"
    }
   ]
  },
  {
   "title": "DS Locked Chans.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(netgear_cm_downstream_channel_power_dbmv{lock_status=\"Locked\"})"
    }
   ]
  },
  {
   "title": "Upstream Power (avg)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(netgear_cm_upstream_channel_power_dbmv > 0)"
    }
   ]
  },
  {
   "title": "US Locked Chans.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(netgear_cm_upstream_channel_power_dbmv{lock_status=\"Locked\"})"
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream Power (dBmV)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netgear_cm_downstream_channel_power_dbmv > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream SnR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "netgear_cm_downstream_channel_snr_db > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Locked Channels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(netgear_cm_downstream_channel_snr_db{lock_status=\"Locked\"})"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upstream Power (dBmV)",
   "type": "timeseries",
   "description": "+7 -> -7 = good range",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netgear_cm_upstream_channel_power_dbmv > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Upstream Locked Channels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(netgear_cm_upstream_channel_power_dbmv{lock_status=\"Locked\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream Unerrored Codewords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(netgear_cm_downstream_channel_unerrored_codewords_total[5m])",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Correctable Codewords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(netgear_cm_downstream_channel_correctable_codewords_total[5m])",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Codewords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(netgear_cm_downstream_channel_uncorrectable_codewords_total[5m])",
     "legendFormat": "{{frequency}}"
    }
   ]
  }
 ]
}